<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Log in_transition-all duration-200</name>
   <tag></tag>
   <elementGuidId>5ced20b4-d55b-4473-91d5-6567b75752be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.transition-all.duration-200</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87f672a6-9449-4c58-9174-317275d3f6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/wero.png?w=128&amp;q=75</value>
      <webElementGuid>adc11914-3af9-49f4-ae4c-554530e8b101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>764fd284-ff33-4e07-8a28-1b14126dd961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>5aff55d9-a9a1-4e73-85bf-211df18fea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all duration-200</value>
      <webElementGuid>00b4767b-8c7e-4f47-89e6-3d61ce277997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/wero.png?w=64&amp;q=75 1x, /images/wero.png?w=128&amp;q=75 2x</value>
      <webElementGuid>08595396-0418-4a87-92b7-39dfdf34aea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Home_container__bCOhY&quot;]/div[@class=&quot;max-w-[1024px] m-auto&quot;]/div[1]/div[@class=&quot;py-5&quot;]/span[1]/img[@class=&quot;transition-all duration-200&quot;]</value>
      <webElementGuid>43e07b67-cbed-42be-a208-caed4441df9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/span/img</value>
      <webElementGuid>24ce0701-1ab6-4eb6-9b07-3498974dc8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>bf63b50a-cec9-4613-b6f4-e959f964b3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/wero.png?w=128&amp;q=75']</value>
      <webElementGuid>02c4f474-2bcd-4967-b972-d9c059bf5610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
