<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_ordernumber</name>
   <tag></tag>
   <elementGuidId>a6a2a407-05ef-4c93-b240-3d327fceb533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ordernumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ordernumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d356e55-451c-4286-a186-8cc409e09c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f6901dcd-600d-48a9-82e7-be81ad83c7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-3 py-1.5 text-[#1C75FA] placeholder-[#1C75FA]/50 border border-solid border-[#1C75FA] transition ease-in-out m-0 focus:[#1C75FA] focus:bg-white focus:border-blue-600 focus:outline-none</value>
      <webElementGuid>8cd30531-88c8-44cc-9517-bcabc2d3905a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ordernumber</value>
      <webElementGuid>1128687b-5f1c-40c7-9d83-a09b74f2736e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>X1E031456</value>
      <webElementGuid>b7bb4233-e1c8-43e4-b52f-c0ee31dd5083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ordernumber&quot;)</value>
      <webElementGuid>940f7b45-01cf-4d66-befa-f859a8195161</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ordernumber']</value>
      <webElementGuid>d846da0c-c1a6-4b98-ba92-7bb30cae89a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div[4]/input</value>
      <webElementGuid>635a2d78-5468-4419-970c-4a575f28cdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>e127489d-4eed-40d9-8ac5-295f31a52822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ordernumber' and @placeholder = 'X1E031456']</value>
      <webElementGuid>62a512c7-f65e-4f7b-ac80-4aa1435b501e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
