<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_repassword</name>
   <tag></tag>
   <elementGuidId>12eac742-f513-4ac4-b072-b68efe6b2df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#repassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eed7bd2-9157-4816-9e9f-234da294af2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>af8b1236-e86b-4356-85d9-48378d0f2b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-3 py-1.5 text-[#1C75FA] placeholder-[#1C75FA]/50 border border-solid border-[#1C75FA] transition ease-in-out m-0 focus:[#1C75FA] focus:bg-white focus:border-blue-600 focus:outline-none</value>
      <webElementGuid>715ccf19-8489-4dfd-ab9a-256d942b2483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>20867b44-bc31-474a-bc55-8a682c862442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repassword&quot;)</value>
      <webElementGuid>01ce3b5c-a309-4747-9dfe-dd0f475d21a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repassword']</value>
      <webElementGuid>1775e2c0-ce34-4ed7-bda0-53b0a5d899d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div[8]/input[2]</value>
      <webElementGuid>db10acbf-0fed-4d60-b959-27730d472bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>14c87bea-2ef0-45c8-8a35-7923d17f0535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'repassword']</value>
      <webElementGuid>06e1d58a-5c82-45c7-bd7d-89d7ec4d5336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
