<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_or Log in to existing account</name>
   <tag></tag>
   <elementGuidId>3dbfd8d8-c201-47f8-8a2f-cba3aea2c80c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='switchToLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#switchToLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec3ecc2b-b379-4f54-975b-5639f9de000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>switchToLogin</value>
      <webElementGuid>43ec863d-1ce9-49fe-965a-cbeae15f29e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[12px] leading-[14px] cursor-pointer text-[#1B1464]/50 hover:text-[#1B1464]</value>
      <webElementGuid>0d18aef0-0bfa-4105-b6e6-641ad848285a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>or Log in to existing account</value>
      <webElementGuid>715ef790-4add-4e15-af44-b83527dc652d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;switchToLogin&quot;)</value>
      <webElementGuid>36748451-6c0c-40a3-81b3-893d3d91e088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='switchToLogin']</value>
      <webElementGuid>b3250b80-5c89-4979-a84e-585308abd815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dialog']/div[4]/a)[2]</value>
      <webElementGuid>2307c91d-7432-4af9-ad67-c43408b8bf38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'or Log in to existing account')]</value>
      <webElementGuid>77c993a2-54be-40f6-930d-dc695abe2814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[1]</value>
      <webElementGuid>03f955e1-f5eb-45aa-9ee9-c80b9d54830c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Re-type Password'])[1]/following::a[1]</value>
      <webElementGuid>5fd6a40c-20bb-41de-9d02-d039688f4662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>f2676d25-5333-424c-995b-c33a79389a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[1]</value>
      <webElementGuid>9262b1e3-fb35-4b09-b5a0-a35f2db216b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='or Log in to existing account']/parent::*</value>
      <webElementGuid>c64c5520-91dc-47da-89d8-685c3cf7fec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/a</value>
      <webElementGuid>7daaf0c2-c6a5-4365-b94d-76dea2439236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'switchToLogin' and (text() = 'or Log in to existing account' or . = 'or Log in to existing account')]</value>
      <webElementGuid>c535d52e-0cbe-499c-88eb-bf284d25465c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
