<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Close</name>
   <tag></tag>
   <elementGuidId>98340632-fa1a-46ee-a605-56e54556da9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='dialog']/div/a)[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>effc7e02-556b-46a3-9dd8-29ece019c74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:cursor-pointer</value>
      <webElementGuid>aa71ca0a-d3f2-4f15-b328-1a7121c33065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>╳</value>
      <webElementGuid>4893530b-cbb1-4806-9240-25d3028def6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Home_container__bCOhY&quot;]/div[@class=&quot;max-w-[1100px] m-auto&quot;]/main[@class=&quot;Home_main__nLjiQ&quot;]/div[@id=&quot;dialog&quot;]/div[@class=&quot;flex flex-row-reverse&quot;]/a[@class=&quot;hover:cursor-pointer&quot;]</value>
      <webElementGuid>e6d6d23d-4fd4-4a07-98fd-ebcb29dd59ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57cf7df7-943b-484d-9cd9-a28f0806eb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:cursor-pointer</value>
      <webElementGuid>735f8b77-97db-415a-b523-1612f12d653c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>╳</value>
      <webElementGuid>fb1df8b4-e8ce-4c1b-9412-c553687773a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Home_container__bCOhY&quot;]/div[@class=&quot;max-w-[1100px] m-auto&quot;]/main[@class=&quot;Home_main__nLjiQ&quot;]/div[@id=&quot;dialog&quot;]/div[@class=&quot;flex flex-row-reverse&quot;]/a[@class=&quot;hover:cursor-pointer&quot;]</value>
      <webElementGuid>30304afb-30d0-4565-8719-6101c18243ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dialog']/div/a)[4]</value>
      <webElementGuid>164413f2-4987-4bc8-9fe9-488ae2f7b201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'╳')])[3]</value>
      <webElementGuid>f0593f23-8588-45c5-b26f-21d4e676cf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or Sign Up'])[1]/following::a[1]</value>
      <webElementGuid>77783fdf-8d6d-4cee-86b8-14b74d26297a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/following::a[2]</value>
      <webElementGuid>165b02dd-412c-4b4d-a827-01e9ab56b167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/preceding::a[1]</value>
      <webElementGuid>cfe0a351-39e2-4e87-948c-c066ad542289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::a[1]</value>
      <webElementGuid>036eb177-a5a1-4295-b4c1-c4a01fd93ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>11438b3f-8d09-4b75-b46e-07d139a9b7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '╳' or . = '╳')]</value>
      <webElementGuid>3db68170-3fd0-4e54-bc68-8145fdb18828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
