<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>87e4710b-f853-4017-a3f5-cb3a9244af4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='email'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register > div.mb-6 > #email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dadcb38e-873c-47e7-9d5a-28838093595c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1cb9a207-616d-4f8a-9d66-4ad29a9e3321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e744d7a8-8f45-468c-bea5-cec28d0d05c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>901c2699-66b1-4422-8a05-054127041ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-3 py-1.5 text-[#1B1464] placeholder-[#1B1464]/50 border border-[1px] border-solid border-[#D9D9D9] transition ease-in-out m-0 focus:[#1B1464] focus:bg-white focus:border-[1px] focus:border-[#1B1464] focus:outline-none</value>
      <webElementGuid>a34650b7-052a-4259-9a89-7f75d123e96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register&quot;)/div[@class=&quot;mb-6&quot;]/input[@id=&quot;email&quot;]</value>
      <webElementGuid>1eb1a380-4eb1-4861-b8d6-5d675570b8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6d98819-f558-48c9-9f2c-0d4e4cdc5301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b4be3046-0c9c-430a-a0fe-e96b946b37ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>48e1691a-e7e7-40de-b5d1-e65f6661bba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a5b000f9-8147-43ee-8c4f-a4fa0d96b861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-3 py-1.5 text-[#1B1464] placeholder-[#1B1464]/50 border border-[1px] border-solid border-[#D9D9D9] transition ease-in-out m-0 focus:[#1B1464] focus:bg-white focus:border-[1px] focus:border-[#1B1464] focus:outline-none</value>
      <webElementGuid>f048d2e7-daf1-48c3-928d-ae72891382dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register&quot;)/div[@class=&quot;mb-6&quot;]/input[@id=&quot;email&quot;]</value>
      <webElementGuid>ede927cf-0190-47a1-bed4-e722b0814a69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='email'])[2]</value>
      <webElementGuid>92f04db9-98fd-41a9-80b8-3f3b414cb805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register']/div[2]/input</value>
      <webElementGuid>86dd0b3b-443a-4c57-a886-f58072980800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/form/div[2]/input</value>
      <webElementGuid>ded93957-93d9-4a54-81cb-2254588cfc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'email' and @name = 'email']</value>
      <webElementGuid>1042097f-4210-4301-9753-9a4ef39a5c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
