<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-type Password_confirmPassword</name>
   <tag></tag>
   <elementGuidId>0689fba5-304b-45e2-8b97-8e4d4db56384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75486c8a-00ef-47af-b3f0-f22ba6e3a1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>805c06e4-8c90-4e09-8f43-9a8c167217ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>2726ffda-0bd4-4d19-920c-0515cbfc420c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>735cf30b-7ccd-49b9-93da-a74dc7ddb79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-3 py-1.5 text-[#1B1464] placeholder-[#1B1464]/50 border border-[1px] border-solid border-[#D9D9D9] transition ease-in-out m-0 focus:[#1B1464] focus:bg-white focus:border-[1px] focus:border-[#1B1464] focus:outline-none</value>
      <webElementGuid>ee1dce5b-09bf-4c0b-813c-e54eda3372cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e4fce14c-cd66-4cd7-bc33-ae4c32057b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>3bef90d0-3b9f-4458-b37f-19af694e59ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(?=.*d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&amp;*]).{8,32}</value>
      <webElementGuid>45e9ac55-9f4f-427d-9f1d-35e21a7e136d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Must contain at least one number and one uppercase and lowercase letter, at least one of this !@#$%^&amp;* special characters, and at least 8 or more characters with max 32 characters in length</value>
      <webElementGuid>ce68291a-b74a-475b-9fb4-15523cc5cd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPassword&quot;)</value>
      <webElementGuid>998ecb17-a18d-425d-85b6-771f025fb57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c972245-7c4c-4347-bffb-37da10617b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e624748-098a-4a5e-b327-03904541ecfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>edfe42d5-a433-40b4-803f-950103d311d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>df53a044-739f-4ce3-92a2-69ca25ecfa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control block w-full px-3 py-1.5 text-[#1B1464] placeholder-[#1B1464]/50 border border-[1px] border-solid border-[#D9D9D9] transition ease-in-out m-0 focus:[#1B1464] focus:bg-white focus:border-[1px] focus:border-[#1B1464] focus:outline-none</value>
      <webElementGuid>23ccd2db-49a3-4b0f-891b-94e71a8f3353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>bb5779d9-7598-41b0-8c2b-80c625e9ea5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>742b47b4-7b21-4428-a74c-d5a83ecca980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(?=.*d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&amp;*]).{8,32}</value>
      <webElementGuid>13b88ac9-dcd8-4970-af88-4831bdc838be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Must contain at least one number and one uppercase and lowercase letter, at least one of this !@#$%^&amp;* special characters, and at least 8 or more characters with max 32 characters in length</value>
      <webElementGuid>1bef71e7-9f30-47cf-9a09-65e8c6faa52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPassword&quot;)</value>
      <webElementGuid>d89c7820-edd0-4ecd-b5e9-7b45881c0012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmPassword']</value>
      <webElementGuid>27da65f5-4ae8-4cc5-a2dd-3e9405e51a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register']/div[7]/div[2]/input</value>
      <webElementGuid>56604bac-e7fe-45a1-b43d-0c0f215669d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>7b5861be-351d-4c37-83ae-2355e66ec42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'confirmPassword' and @name = 'confirmPassword' and @title = 'Must contain at least one number and one uppercase and lowercase letter, at least one of this !@#$%^&amp;* special characters, and at least 8 or more characters with max 32 characters in length']</value>
      <webElementGuid>79b3aeeb-7e6d-4251-9ca1-c0e326c640f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
