<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Close</name>
   <tag></tag>
   <elementGuidId>36ae30e9-532c-47f7-a146-74dab09e0751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='dialog']/div/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e57bffc-c396-4367-a707-31e4e94af860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:cursor-pointer</value>
      <webElementGuid>ba5a724c-5115-496a-83fa-742ebee1d494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>╳</value>
      <webElementGuid>a6c5ced3-95a5-4d62-ad6e-3e0f28df64e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Home_container__bCOhY&quot;]/div[@class=&quot;max-w-[1100px] m-auto&quot;]/main[@class=&quot;Home_main__nLjiQ&quot;]/div[@id=&quot;dialog&quot;]/div[@class=&quot;flex flex-row-reverse&quot;]/a[@class=&quot;hover:cursor-pointer&quot;]</value>
      <webElementGuid>317ac038-8df0-4c7b-b823-2c887e59ba6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dialog']/div/a)[2]</value>
      <webElementGuid>e712a813-9d3b-4ae6-a812-182f3e206be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'╳')])[2]</value>
      <webElementGuid>f514f8ab-6053-461a-b4fe-28b2a6482079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have sent a verification email to'])[1]/following::a[1]</value>
      <webElementGuid>cbc2ef04-dbab-482a-9327-10b2bb12df54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='╳'])[1]/following::a[1]</value>
      <webElementGuid>5d5d5c62-ca71-4a50-b10b-3128afb357ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[2]/preceding::a[1]</value>
      <webElementGuid>4f677584-4789-41f5-952a-651c03e6ef39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email / Username'])[1]/preceding::a[1]</value>
      <webElementGuid>5238f965-f075-4b86-82ff-a27e33fd5103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>1937f069-f175-4bf0-bebb-34e43a2b26b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '╳' or . = '╳')]</value>
      <webElementGuid>c51742d5-3a08-4427-b384-aad479a8bd95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
