<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Matchmake</name>
   <tag></tag>
   <elementGuidId>b2f80f1c-8d94-4e94-86b0-83a031ae8629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f534d07-b66a-4fd7-8d2c-b3563dc27b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-500 px-5 hover:text-gray-700 focus:text-gray-700 mr-4 hover:cursor-pointer</value>
      <webElementGuid>1d45cadb-0366-483b-8316-8a4c4820648f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8779ec6d-d022-490e-a135-f5f0d5162ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Matchmake</value>
      <webElementGuid>f806e4de-ffc1-4883-90f8-712dcfb065eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Home_container__bCOhY&quot;]/div[@class=&quot;max-w-[1100px] m-auto&quot;]/nav[@class=&quot;relative w-full flex flex-wrap items-center justify-between py-4 text-gray-500 navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container-fluid w-full flex flex-wrap items-center justify-between&quot;]/div[@class=&quot;flex items-center relative&quot;]/a[@class=&quot;text-gray-500 px-5 hover:text-gray-700 focus:text-gray-700 mr-4 hover:cursor-pointer&quot;]</value>
      <webElementGuid>886b3675-5bd1-4b72-9992-df5510be29ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/div/div/a</value>
      <webElementGuid>346cecc2-01fe-43cf-9702-96223a56581c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Matchmake')]</value>
      <webElementGuid>66ff0ca6-946a-4c78-976c-0dacc7d939c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::a[1]</value>
      <webElementGuid>90049aa1-f518-4a31-a444-a90a16684c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='╳'])[1]/preceding::a[2]</value>
      <webElementGuid>ff0cb620-389a-4bf0-9a9e-e813e0e6dbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Matchmake']/parent::*</value>
      <webElementGuid>283850b5-4f3a-4016-8b24-81eabadbaec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>ae99a6fe-cad2-431f-a851-d4b02879eb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6004136f-0a97-44c1-886a-9960accbcd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Matchmake' or . = 'Matchmake')]</value>
      <webElementGuid>6411b181-6d7b-49b5-b2fd-95d7b2daf8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
